wget "https://asil.tv/wp-content/uploads/2023/08/الحلقة الاولى- الزعبي.mp4" -O "media/post_3634_الحلقة الاولى- الزعبي.mp4"
wget "https://asil.tv/wp-content/uploads/2023/08/الحلقة الاولى- الزعبي.mp4" -O "media/post_3634_الحلقة الاولى- الزعبي.mp4"
wget "https://asil.tv/wp-content/uploads/2023/08/الحلقة الثانية- الزعبي.mp4" -O "media/post_3648_الحلقة الثانية- الزعبي.mp4"
wget "https://asil.tv/wp-content/uploads/2023/08/الحلقة الثانية- الزعبي.mp4" -O "media/post_3648_الحلقة الثانية- الزعبي.mp4"
wget "https://asil.tv/wp-content/uploads/2023/08/الحلقة الثالثة- الزعيي.mp4" -O "media/post_3652_الحلقة الثالثة- الزعيي.mp4"
wget "https://asil.tv/wp-content/uploads/2023/08/الحلقة الثالثة- الزعيي.mp4" -O "media/post_3652_الحلقة الثالثة- الزعيي.mp4"
wget "https://asil.tv/wp-content/uploads/2023/08/الحلقة الرابعة - الزعبي.mp4" -O "media/post_3655_الحلقة الرابعة - الزعبي.mp4"
wget "https://asil.tv/wp-content/uploads/2023/08/الحلقة الرابعة - الزعبي.mp4" -O "media/post_3655_الحلقة الرابعة - الزعبي.mp4"
wget "https://asil.tv/wp-content/uploads/2024/01/الحلقة الثانية- الزعتري.mp4" -O "media/post_7397_الحلقة الثانية- الزعتري.mp4"
wget "https://asil.tv/wp-content/uploads/2024/01/الحلقة الثانية- الزعتري.mp4" -O "media/post_7397_الحلقة الثانية- الزعتري.mp4"