version: "3.8"

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    environment:
      - 'OLLAMA_BASE_URL=http://192.168.2.160:11434'  # سرور اصلی که Ollama روی آن در حال اجرا است
    ports:
      - 3005:8080  # پورت رابط کاربری وب
    volumes:
      - ./open-webui:/app/backend/data
    restart: unless-stopped
